### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by bibinvargheset** [QTinman/freqStratStat#1]
mainwindow.h:4:10: fatal error: QMainWindow: No such file or directory
    4 | #include <QMainWindow>
      |          ^~~~~~~~~~~~~
compilation terminated.

[Done] exited with code=1 in 0.088 seconds

**Comment by QTinman** [comment]
QMainWindow comes with QT, you should find it under Qt/6.0.3/gcc_64/include/QtWidgets/
If not your QT installation might be incomplete.
